// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: game.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------- Game Entity -----------
type Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Genre         string                 `protobuf:"bytes,2,opt,name=genre,proto3" json:"genre,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Release       int32                  `protobuf:"varint,4,opt,name=release,proto3" json:"release,omitempty"`
	Rating        float32                `protobuf:"fixed32,5,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *Game) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Game) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *Game) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Game) GetRelease() int32 {
	if x != nil {
		return x.Release
	}
	return 0
}

func (x *Game) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

// ----------- Responses -----------
type GameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameResponse) Reset() {
	*x = GameResponse{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameResponse) ProtoMessage() {}

func (x *GameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameResponse.ProtoReflect.Descriptor instead.
func (*GameResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *GameResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type GamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          []*Game                `protobuf:"bytes,1,rep,name=game,proto3" json:"game,omitempty"`
	GamesCount    int32                  `protobuf:"varint,2,opt,name=gamesCount,proto3" json:"gamesCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GamesResponse) Reset() {
	*x = GamesResponse{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamesResponse) ProtoMessage() {}

func (x *GamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamesResponse.ProtoReflect.Descriptor instead.
func (*GamesResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *GamesResponse) GetGame() []*Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *GamesResponse) GetGamesCount() int32 {
	if x != nil {
		return x.GamesCount
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SearchAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"` // Optional filters by fields
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAllRequest) Reset() {
	*x = SearchAllRequest{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAllRequest) ProtoMessage() {}

func (x *SearchAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAllRequest.ProtoReflect.Descriptor instead.
func (*SearchAllRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *SearchAllRequest) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *SearchAllRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchAllRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByNameRequest) Reset() {
	*x = SearchByNameRequest{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByNameRequest) ProtoMessage() {}

func (x *SearchByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByNameRequest.ProtoReflect.Descriptor instead.
func (*SearchByNameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *SearchByNameRequest) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type SearchByGenreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genre         string                 `protobuf:"bytes,1,opt,name=genre,proto3" json:"genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByGenreRequest) Reset() {
	*x = SearchByGenreRequest{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByGenreRequest) ProtoMessage() {}

func (x *SearchByGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByGenreRequest.ProtoReflect.Descriptor instead.
func (*SearchByGenreRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *SearchByGenreRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

type SearchByPlatformRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByPlatformRequest) Reset() {
	*x = SearchByPlatformRequest{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByPlatformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByPlatformRequest) ProtoMessage() {}

func (x *SearchByPlatformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByPlatformRequest.ProtoReflect.Descriptor instead.
func (*SearchByPlatformRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *SearchByPlatformRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type SearchByReleaseRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromYear      int32                  `protobuf:"varint,1,opt,name=from_year,json=fromYear,proto3" json:"from_year,omitempty"`
	ToYear        int32                  `protobuf:"varint,2,opt,name=to_year,json=toYear,proto3" json:"to_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByReleaseRangeRequest) Reset() {
	*x = SearchByReleaseRangeRequest{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByReleaseRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByReleaseRangeRequest) ProtoMessage() {}

func (x *SearchByReleaseRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByReleaseRangeRequest.ProtoReflect.Descriptor instead.
func (*SearchByReleaseRangeRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *SearchByReleaseRangeRequest) GetFromYear() int32 {
	if x != nil {
		return x.FromYear
	}
	return 0
}

func (x *SearchByReleaseRangeRequest) GetToYear() int32 {
	if x != nil {
		return x.ToYear
	}
	return 0
}

type SearchByRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinRating     float32                `protobuf:"fixed32,1,opt,name=min_rating,json=minRating,proto3" json:"min_rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByRatingRequest) Reset() {
	*x = SearchByRatingRequest{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByRatingRequest) ProtoMessage() {}

func (x *SearchByRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByRatingRequest.ProtoReflect.Descriptor instead.
func (*SearchByRatingRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *SearchByRatingRequest) GetMinRating() float32 {
	if x != nil {
		return x.MinRating
	}
	return 0
}

type AdvancedSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Genre         string                 `protobuf:"bytes,2,opt,name=genre,proto3" json:"genre,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	ReleaseFrom   int32                  `protobuf:"varint,4,opt,name=release_from,json=releaseFrom,proto3" json:"release_from,omitempty"`
	ReleaseTo     int32                  `protobuf:"varint,5,opt,name=release_to,json=releaseTo,proto3" json:"release_to,omitempty"`
	MinRating     float32                `protobuf:"fixed32,6,opt,name=min_rating,json=minRating,proto3" json:"min_rating,omitempty"`
	Limit         int64                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvancedSearchRequest) Reset() {
	*x = AdvancedSearchRequest{}
	mi := &file_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvancedSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvancedSearchRequest) ProtoMessage() {}

func (x *AdvancedSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvancedSearchRequest.ProtoReflect.Descriptor instead.
func (*AdvancedSearchRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *AdvancedSearchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdvancedSearchRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *AdvancedSearchRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AdvancedSearchRequest) GetReleaseFrom() int32 {
	if x != nil {
		return x.ReleaseFrom
	}
	return 0
}

func (x *AdvancedSearchRequest) GetReleaseTo() int32 {
	if x != nil {
		return x.ReleaseTo
	}
	return 0
}

func (x *AdvancedSearchRequest) GetMinRating() float32 {
	if x != nil {
		return x.MinRating
	}
	return 0
}

func (x *AdvancedSearchRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AdvancedSearchRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{11}
}

func (x *CreateGameRequest) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type UpdateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Game          *Game                  `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameRequest) Reset() {
	*x = UpdateGameRequest{}
	mi := &file_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameRequest) ProtoMessage() {}

func (x *UpdateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameRequest.ProtoReflect.Descriptor instead.
func (*UpdateGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateGameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGameRequest) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type DeleteGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGameRequest) Reset() {
	*x = DeleteGameRequest{}
	mi := &file_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameRequest) ProtoMessage() {}

func (x *DeleteGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameRequest.ProtoReflect.Descriptor instead.
func (*DeleteGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteGameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x04game\x1a\x1cgoogle/api/annotations.proto\"~\n" +
	"\x04Game\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05genre\x18\x02 \x01(\tR\x05genre\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x18\n" +
	"\arelease\x18\x04 \x01(\x05R\arelease\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x02R\x06rating\".\n" +
	"\fGameResponse\x12\x1e\n" +
	"\x04game\x18\x01 \x01(\v2\n" +
	".game.GameR\x04game\"O\n" +
	"\rGamesResponse\x12\x1e\n" +
	"\x04game\x18\x01 \x03(\v2\n" +
	".game.GameR\x04game\x12\x1e\n" +
	"\n" +
	"gamesCount\x18\x02 \x01(\x05R\n" +
	"gamesCount\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"`\n" +
	"\x10SearchAllRequest\x12\x1e\n" +
	"\x04game\x18\x01 \x01(\v2\n" +
	".game.GameR\x04game\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"5\n" +
	"\x13SearchByNameRequest\x12\x1e\n" +
	"\x04game\x18\x01 \x01(\v2\n" +
	".game.GameR\x04game\",\n" +
	"\x14SearchByGenreRequest\x12\x14\n" +
	"\x05genre\x18\x01 \x01(\tR\x05genre\"5\n" +
	"\x17SearchByPlatformRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\"S\n" +
	"\x1bSearchByReleaseRangeRequest\x12\x1b\n" +
	"\tfrom_year\x18\x01 \x01(\x05R\bfromYear\x12\x17\n" +
	"\ato_year\x18\x02 \x01(\x05R\x06toYear\"6\n" +
	"\x15SearchByRatingRequest\x12\x1d\n" +
	"\n" +
	"min_rating\x18\x01 \x01(\x02R\tminRating\"\xec\x01\n" +
	"\x15AdvancedSearchRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05genre\x18\x02 \x01(\tR\x05genre\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12!\n" +
	"\frelease_from\x18\x04 \x01(\x05R\vreleaseFrom\x12\x1d\n" +
	"\n" +
	"release_to\x18\x05 \x01(\x05R\treleaseTo\x12\x1d\n" +
	"\n" +
	"min_rating\x18\x06 \x01(\x02R\tminRating\x12\x14\n" +
	"\x05limit\x18\a \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\b \x01(\x03R\x06offset\"3\n" +
	"\x11CreateGameRequest\x12\x1e\n" +
	"\x04game\x18\x01 \x01(\v2\n" +
	".game.GameR\x04game\"G\n" +
	"\x11UpdateGameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\x04game\x18\x02 \x01(\v2\n" +
	".game.GameR\x04game\"'\n" +
	"\x11DeleteGameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\x89\a\n" +
	"\x05Games\x12G\n" +
	"\tSearchAll\x12\x16.game.SearchAllRequest\x1a\x13.game.GamesResponse\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/game\x12X\n" +
	"\fSearchByName\x12\x19.game.SearchByNameRequest\x1a\x12.game.GameResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/game/{game.name}\x12]\n" +
	"\rSearchByGenre\x12\x1a.game.SearchByGenreRequest\x1a\x13.game.GamesResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/game/genre/{genre}\x12i\n" +
	"\x10SearchByPlatform\x12\x1d.game.SearchByPlatformRequest\x1a\x13.game.GamesResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/game/platform/{platform}\x12e\n" +
	"\x14SearchByReleaseRange\x12!.game.SearchByReleaseRangeRequest\x1a\x13.game.GamesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/game/release\x12X\n" +
	"\x0eSearchByRating\x12\x1b.game.SearchByRatingRequest\x1a\x13.game.GamesResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/game/rating\x12X\n" +
	"\x0eAdvancedSearch\x12\x1b.game.AdvancedSearchRequest\x1a\x13.game.GamesResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/game/search\x12N\n" +
	"\n" +
	"CreateGame\x12\x17.game.CreateGameRequest\x1a\x12.game.GameResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x04game\"\x05/game\x12U\n" +
	"\n" +
	"UpdateGame\x12\x17.game.UpdateGameRequest\x1a\x12.game.GameResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x04game\x1a\f/game/{name}\x12Q\n" +
	"\n" +
	"DeleteGame\x12\x17.game.DeleteGameRequest\x1a\x14.game.DeleteResponse\"\x14\x82\xd3\xe4\x93\x02\x0e*\f/game/{name}B\tZ\a.;protob\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_game_proto_goTypes = []any{
	(*Game)(nil),                        // 0: game.Game
	(*GameResponse)(nil),                // 1: game.GameResponse
	(*GamesResponse)(nil),               // 2: game.GamesResponse
	(*DeleteResponse)(nil),              // 3: game.DeleteResponse
	(*SearchAllRequest)(nil),            // 4: game.SearchAllRequest
	(*SearchByNameRequest)(nil),         // 5: game.SearchByNameRequest
	(*SearchByGenreRequest)(nil),        // 6: game.SearchByGenreRequest
	(*SearchByPlatformRequest)(nil),     // 7: game.SearchByPlatformRequest
	(*SearchByReleaseRangeRequest)(nil), // 8: game.SearchByReleaseRangeRequest
	(*SearchByRatingRequest)(nil),       // 9: game.SearchByRatingRequest
	(*AdvancedSearchRequest)(nil),       // 10: game.AdvancedSearchRequest
	(*CreateGameRequest)(nil),           // 11: game.CreateGameRequest
	(*UpdateGameRequest)(nil),           // 12: game.UpdateGameRequest
	(*DeleteGameRequest)(nil),           // 13: game.DeleteGameRequest
}
var file_game_proto_depIdxs = []int32{
	0,  // 0: game.GameResponse.game:type_name -> game.Game
	0,  // 1: game.GamesResponse.game:type_name -> game.Game
	0,  // 2: game.SearchAllRequest.game:type_name -> game.Game
	0,  // 3: game.SearchByNameRequest.game:type_name -> game.Game
	0,  // 4: game.CreateGameRequest.game:type_name -> game.Game
	0,  // 5: game.UpdateGameRequest.game:type_name -> game.Game
	4,  // 6: game.Games.SearchAll:input_type -> game.SearchAllRequest
	5,  // 7: game.Games.SearchByName:input_type -> game.SearchByNameRequest
	6,  // 8: game.Games.SearchByGenre:input_type -> game.SearchByGenreRequest
	7,  // 9: game.Games.SearchByPlatform:input_type -> game.SearchByPlatformRequest
	8,  // 10: game.Games.SearchByReleaseRange:input_type -> game.SearchByReleaseRangeRequest
	9,  // 11: game.Games.SearchByRating:input_type -> game.SearchByRatingRequest
	10, // 12: game.Games.AdvancedSearch:input_type -> game.AdvancedSearchRequest
	11, // 13: game.Games.CreateGame:input_type -> game.CreateGameRequest
	12, // 14: game.Games.UpdateGame:input_type -> game.UpdateGameRequest
	13, // 15: game.Games.DeleteGame:input_type -> game.DeleteGameRequest
	2,  // 16: game.Games.SearchAll:output_type -> game.GamesResponse
	1,  // 17: game.Games.SearchByName:output_type -> game.GameResponse
	2,  // 18: game.Games.SearchByGenre:output_type -> game.GamesResponse
	2,  // 19: game.Games.SearchByPlatform:output_type -> game.GamesResponse
	2,  // 20: game.Games.SearchByReleaseRange:output_type -> game.GamesResponse
	2,  // 21: game.Games.SearchByRating:output_type -> game.GamesResponse
	2,  // 22: game.Games.AdvancedSearch:output_type -> game.GamesResponse
	1,  // 23: game.Games.CreateGame:output_type -> game.GameResponse
	1,  // 24: game.Games.UpdateGame:output_type -> game.GameResponse
	3,  // 25: game.Games.DeleteGame:output_type -> game.DeleteResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
